FROM php:8.3-apache

# Enable Apache modules
RUN docker-php-ext-install pdo pdo_mysql \
    && a2enmod rewrite

WORKDIR /var/www/html

# Copy app files
COPY . .

EXPOSE 80
CMD ["apache2-foreground"]

# CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
