# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .
RUN go build -o main .

# Run stage (smaller image)
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]

