# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]


#To run the Docker image:
#docker build -t node-app:v1 .
#docker run -d -p 3000:3000 node-app:v1